# -*- coding: utf-8 -*-
"""Image to Pencil Sketch with Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TwWS6auKSp9kvjquJ5ubqooYon3FsQs6

### BEGINNER LEVEL TASK


# Image to Pencil Sketch with Python
"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline

import cv2
import matplotlib.pyplot as plt
from PIL import Image
from IPython.display import display,clear_output

image=cv2.imread('Zebra.jpg')

display(Image.fromarray(image))

image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
display(Image.fromarray(gray_image))

inverted_image = 255 - gray_image
display(Image.fromarray(inverted_image))

blurred = cv2.GaussianBlur(inverted_image, (21, 21), 0)

invert_blurred = 255 - blurred
pencil_sketch = cv2.divide(gray_image, invert_blurred, scale=256.0)
display(Image.fromarray(pencil_sketch))

plt.figure(figsize=(18, 6))

# Display the color image on the left subplot
plt.subplot(1, 3, 1)
plt.imshow(image_rgb)
plt.title('Color Image')
plt.axis('off')

# Display the grayscale image in the middle subplot
plt.subplot(1, 3, 2)
plt.imshow(gray_image, cmap='gray')
plt.title('Grayscale Image')
plt.axis('off')

# Display the pencil sketch image on the right subplot
plt.subplot(1, 3, 3)
plt.imshow(pencil_sketch, cmap='gray')
plt.title('Pencil Sketch')
plt.axis('off')

# Show the figure with all three images
plt.show()